### ISSUE TITLE
安卓13无法访问外置存储

### ISSUE THREAD

**Issue by Rinaex** [zeromake/ONScripter-zero#1]
![Screenshot_2024-03-31-15-45-29-744_com zeromake o](https://github.com/zeromake/ONScripter-zero/assets/59467262/20699d93-c0a3-4b29-8f25-032f91c5fc68)

**Comment by zeromake** [comment]
@Rinaex 
应该是你刚安装，就滚动到最下面选择 `其它…`，我之前写的默认回退目录是 `/` android 是不允许访问的，你可以先选择游戏路径里的目录以后再走 … 去选择其它目录，或者试试我刚刚改了的默认目录(/mnt)的 [v0.9.17](https://github.com/zeromake/ONScripter-zero/releases/tag/v0.9.17)

**Comment by zeromake** [comment]
@Rinaex 没有反馈我就关闭了，有问题你可以reopen

**Comment by Rinaex** [comment]
@zeromake 感谢回复,因为不常用到所以今天才看到
我试用了v0.9.19,它还是找不到外置存储
附带一个视频
https://github.com/zeromake/ONScripter-zero/assets/59467262/a986c600-58a0-475d-87c9-bf325b2c8c09

**Comment by zeromake** [comment]
@Rinaex 
可能是一个比较少见的路径，而且 /mnt 下面没有见到……，可以考虑把这个路径直接报告给我，我直接内置进去

**Comment by Rinaex** [comment]
@zeromake 问了一些人,大多数人的外置存储目录都是 `/storage/sdcard0`   少数人使用的是`/mnt/sdcard`

**Comment by zeromake** [comment]
@Rinaex 
[v0.9.20](https://github.com/zeromake/ONScripter-zero/releases/tag/v0.9.20) 
重做了点击其它的选择目录效果，现在能够在外置存储里没有 ons, mine 目录的情况下选择外置存储根路径去选择自定义路径了（之前的逻辑有问题没有 ons, mine 目录一定无法选择其它路径……）。
现在写了一堆可能的外置或者内置存储路径：
[Globals.java](https://github.com/zeromake/ONScripter-zero/blob/master/project/android/app/src/main/java/com/zeromake/onscripter/Globals.java#L11)

**Comment by zeromake** [comment]
![其它选项](https://github.com/zeromake/ONScripter-zero/assets/8318747/e0ec3630-f3c1-40d1-b009-c8f595bc2f2a)
![所有可以访问的存储根路径](https://github.com/zeromake/ONScripter-zero/assets/8318747/7c838703-147d-4f05-b04c-42d45c243be6)

**Comment by Rinaex** [comment]
@zeromake 好耶 可以用了
