### ISSUE TITLE
游戏bgm未能正常播放

### ISSUE THREAD

**Issue by Rinaex** [zeromake/ONScripter-zero#2]
安卓版运行[缘之空](http://zi6.cc/.【夏风】/.【夏风-1】/安卓/ONS/【ONS】【1080p】缘之空.7z)时，没有bgm，其他声音都正常，在鉴赏里面也无法播放

使用[OnscripterYuri](https://github.com/YuriSizuku/OnscripterYuri)测试了一下游戏bgm是正常的

测试环境小米hyperos1.0.60

**Comment by zeromake** [comment]
@Rinaex 简单看了一下是 mp3 格式的，应该是我没给 sdl2_mixer 搞单独的 mp3 解码器导致的

**Comment by zeromake** [comment]
@Rinaex 已发布 https://github.com/zeromake/ONScripter-zero/releases/tag/v0.9.21 ，我手机测试后有 bgm 了，不过不打 nsa 解压慢到快睡着了……，小文体太多了
