### ISSUE TITLE
无法连续使用多个bgm命令

### ISSUE THREAD

**Issue by icey9527** [zeromake/ONScripter-zero#3]
无法连续使用多个bgm命令

会导致bgm播放失败，中间插入bgmstop也不行，但在中间插入print 1或click可以使其正常播放

顺便请教一下iOS版的使用方式，我像ONSPlayer一样放到Documents，但似乎并没有效果
![2a3b3b3b919ab029516cba1969cd6980_720](https://github.com/user-attachments/assets/3b1d81cb-108b-4b95-b8d9-f8ea00132c02)

**Comment by icey9527** [comment]
又试了几次，背景更新的缘故，背景更新bgm才会播放

**Comment by zeromake** [comment]
@icey9527 
bgm 指令应该没有改过，我看看
ios 版我只是拿了上古 iphone6p 测试的，我有点忘记是要放哪里我找找。

**Comment by zeromake** [comment]
@icey9527 
翻了一下代码应该是在应用的 Document/game 目录里

**Comment by icey9527** [comment]
感谢，ios可以用了

**Comment by zeromake** [comment]
@icey9527 
windows 上测试并未发现连续使用多个 bgm 命令有问题，以下测试 0.txt 正常播放了 `02.ogg`.
```
;mode800
*define
game
*start
bgm "13.ogg"
bgm "01.ogg"
bgm "02.ogg"
测试文本2@
```

不过我改了一个 wave 指令在切换同一个通道语音时会出现上一次的结束回调把下一次的语音回收
https://github.com/zeromake/ONScripter-zero/compare/v0.9.23...v0.9.24

你可以试试 [v0.9.24](https://github.com/zeromake/ONScripter-zero/releases/tag/v0.9.24) 是否修复

**Comment by icey9527** [comment]
@zeromake 正常播放了，感谢大佬
